/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.sql.ResultSet;
import java.sql.SQLException;
import Negocio.ClsNEmpleado;
import Entidad.ClsEEmpleado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arnold
 */
public class FrmMEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FrmMEmpleado
     */
    
    ClsNEmpleado objNEmp = new ClsNEmpleado();
    ClsEEmpleado objEEmp = new ClsEEmpleado();
    
    DefaultTableModel modelo=new DefaultTableModel();
    
    public FrmMEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo.addColumn("Dni");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Cargo");
        modelo.addColumn("Estado");
        modelo.addColumn("Clave");
        this.Tabla.setModel(modelo);
        fecha_actual();
        
    }
    
    public void fecha_actual() { 
        Date sisFecha = new Date(); 
        SimpleDateFormat formato= new SimpleDateFormat("dd-MM-YYYY");
        Fecha.setText(formato.format(sisFecha));
        
        Timer tiempo = new Timer(100, new FrmMEmpleado.horas());
        tiempo.start();
    }
    
    class horas implements ActionListener{
        public void  actionPerformed(ActionEvent e){
            Date sistHora = new Date();
            String pmAm = "hh:mm:ss a";
            SimpleDateFormat format = new SimpleDateFormat(pmAm);
            Calendar hoy = Calendar.getInstance(); 
            Hora.setText(String.format(format.format(sistHora),hoy));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        Fecha = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelDni = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE EMPLEADOS");

        jLabel2.setText("ingrese dato de busqueda:");

        jLabel3.setText("Estado:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEstado.setText("Cambiar");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        Fecha.setText("dd-MM-YYYY");

        jLabel16.setText("Hora:");

        Hora.setText("hh--mm");

        jLabel11.setText("Empleado DNI:");

        labelDni.setText("Nro DNI");

        jLabel15.setText("Fecha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEstado)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscar)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnLimpiar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevo)
                                .addGap(66, 66, 66))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(57, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Hora)))
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Fecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(labelDni))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hora)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnListar)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(btnEstado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnSalir))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        
        MtdlimpiarTabla();
        MtdListar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        MtdlimpiarTabla();
        ResultSet rs;
        
        objEEmp.setB(txtDato.getText());
        int flag = 0;
        
            try {
                Integer.parseInt(txtDato.getText());
                flag = 1;
            }
            catch(Exception e) {
                
            }
            
         if (flag==1){
             
            rs=objNEmp.MtdBuscar(objEEmp);
            try {
            while (rs.next())
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
            
            rs=objNEmp.MtdBuscar4(objEEmp);
            try {
            while (rs.next())
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
            rs=objNEmp.MtdBuscar5(objEEmp);
            try {
            while (rs.next())
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
     
         }
         else{
             
            rs=objNEmp.MtdBuscar1(objEEmp);
            try {
            while (rs.next())
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
            rs=objNEmp.MtdBuscar2(objEEmp);
            try {
            while (rs.next())
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
            rs=objNEmp.MtdBuscar3(objEEmp);
            try {
            while (rs.next())
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
            rs=objNEmp.MtdBuscar5(objEEmp);
            try {
            while (rs.next())
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
         }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        MtdlimpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fila = Tabla.getSelectedRow();
        if(fila>=0){
            objNEmp.MtdEliminar(Integer.parseInt(Tabla.getValueAt(fila, 0).toString()));
            modelo.removeRow(fila);
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed

        int fila = Tabla.getSelectedRow();
        
        if(fila>=0){
            
            if(Tabla.getValueAt(fila, 4).toString().equalsIgnoreCase("I")){
                //estado = "1";
                Tabla.getValueAt(fila, 4).toString();
                objNEmp.MtdEstado("A",Integer.parseInt(Tabla.getValueAt(fila, 0).toString()));
            }
            
            if(Tabla.getValueAt(fila, 4).toString().equalsIgnoreCase("A")){
                //estado = "0";
                Tabla.getValueAt(fila, 4).toString();        
                objNEmp.MtdEstado("I",Integer.parseInt(Tabla.getValueAt(fila, 0).toString()));
            }  
            modelo.removeRow(fila);
            MtdlimpiarTabla();   
             
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        }
        
        
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
        FrmREmpleado FrmREmp = new FrmREmpleado();
        FrmREmp.show();
        this.dispose();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmLogin FrmLog= new FrmLogin();
        FrmLog.show();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void MtdListar() {
        ResultSet rs;//iniciando nuestro contenedor de datos
        rs=objNEmp.MtdListar_Empleados();//rs contiene el resultad de la consulta al BD
        try {
            while (rs.next())//inicia desde el primer elemento hasta el final de la consulta DB
            {
                modelo.addRow(new Object[]{rs.getInt("dni"),rs.getString("nombres"),rs.getString("apellidos"),
                    rs.getString("cargo"),rs.getString("estado"),rs.getString("clave")});
            }
            Tabla.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    private void MtdlimpiarTabla(){ 
        modelo.getDataVector().removeAllElements();
        Tabla.updateUI();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelDni;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
