/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsECategoria;
import Entidad.ClsEProducto;
import Negocio.ClsNVenta;
import Presentacion.FrmLogin;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import Negocio.*;
import Entidad.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arnold
 */
public class FrmVenta extends javax.swing.JFrame {

    /**
     * Creates new form FrmVenta
     */
    
    ClsNCategoria CNCate = new ClsNCategoria();
    ClsNProducto CNProd = new ClsNProducto();
    ClsECliente objECliente= new ClsECliente();
    ClsEStock objEStock = new ClsEStock();
    ClsEVenta objEVenta = new ClsEVenta();
    ClsEDetalleVenta objEDVenta = new ClsEDetalleVenta();
    ClsEProducto objEProducto = new ClsEProducto();
    ClsNVenta objNventa=new ClsNVenta();
    
    DefaultTableModel modelo=new DefaultTableModel();
    
    
    
    public FrmVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        CNCate.Mtd_listar_categorias(cmbxCategoria);
        CNProd.Mtd_Sin_Categoria(cmbxProducto);
        txtSPC.setVisible(false);
        LabelMarca.getText();
        txtProdNombre.setVisible(false);
        txtMarca.setVisible(false);
        txtProdCodigo.setVisible(false);
        txtProdPrecio.setVisible(false);
        
        modelo.addColumn("Cant.");
        modelo.addColumn("Cod_Prod");
        modelo.addColumn("Nombre");
        modelo.addColumn("Marca");
        modelo.addColumn("Precio S/.");
        modelo.addColumn("SPC");
        
        this.TablaProductos.setModel(modelo);
        TablaProductos.getColumnModel().getColumn(0).setPreferredWidth(10);
        TablaProductos.getColumnModel().getColumn(1).setPreferredWidth(40);
        TablaProductos.getColumnModel().getColumn(2).setPreferredWidth(270);
        TablaProductos.getColumnModel().getColumn(3).setPreferredWidth(70);
        TablaProductos.getColumnModel().getColumn(4).setPreferredWidth(40);
        TablaProductos.getColumnModel().getColumn(5).setPreferredWidth(15);

        txtcantidad.setText("1"); 
        txtTotal.setText("0");
        txtTotalVenta.setText("0");
        txtIGV.setText("0");
        txtTotal.setEditable(false);
        txtTotalVenta.setEditable(false);
        txtIGV.setEditable(false);
        fecha_actual();
        MtdId_venta();

        txtDniCliente.setText("");
        txtNombreCliente.setText("");
        txtNombreCliente.setEnabled(false);
        txtApellidosCliente.setEnabled(false);
        txtApellidosCliente.setText("");
        txtNombreCliente.setEditable(false);
        txtApellidosCliente.setEditable(false);
        btnAgregar.setEnabled(false);
   
    }
    
    public void fecha_actual() { 
        Date sisFecha = new Date(); 
        SimpleDateFormat formato= new SimpleDateFormat("YYYY-MM-dd");
        labelFecha.setText(formato.format(sisFecha));
        
        Timer tiempo = new Timer(100, new FrmVenta.horas());
        tiempo.start();
    }
    
    class horas implements ActionListener{
        public void  actionPerformed(ActionEvent e){
            Date sistHora = new Date();
            String pmAm = "HH:mm:ss";
            SimpleDateFormat format = new SimpleDateFormat(pmAm);
            Calendar hoy = Calendar.getInstance(); 
            labelHora.setText(String.format(format.format(sistHora),hoy));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcantidad = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtProdCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidosCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        btnClienteCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        LabelCantidad = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        txtProdNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelIdVenta = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbxCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbxProducto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        LabelMarca = new javax.swing.JLabel();
        txtProdPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelDniEmpleado = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtSPC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        txtIGV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtcantidad.setText("CantCompra");

        txtMarca.setText("Marca");

        txtProdCodigo.setText("ProdCodigo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente"));

        jLabel1.setText("Nombre:");

        jLabel3.setText("Apellidos:");

        jLabel12.setText("DNI:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnClienteCancelar.setText("Reset");
        btnClienteCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(25, 25, 25))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDniCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(btnBuscar))
                    .addComponent(txtApellidosCliente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClienteCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoCliente))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteCancelar))
                .addGap(14, 14, 14))
        );

        jLabel11.setText("Nro Stock:");

        LabelCantidad.setText("stock");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        txtProdNombre.setText("ProdNombre");

        jLabel5.setText("ID de venta:");

        labelIdVenta.setText("ID Numero");

        jLabel7.setText("Categoria:");

        cmbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxCategoriaItemStateChanged(evt);
            }
        });
        cmbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxCategoriaActionPerformed(evt);
            }
        });

        jLabel8.setText("Producto:");

        cmbxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxProductoItemStateChanged(evt);
            }
        });

        jLabel9.setText("Marca:");

        LabelMarca.setText("marca");

        txtProdPrecio.setText("ProdPrecio");

        jLabel10.setText("Cantidad: ");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        jLabel2.setText("Total: S/.");

        jLabel4.setText("Fecha:");

        labelFecha.setText("dd-MM-YYYY");

        jLabel13.setText("Hora:");

        labelHora.setText("hh--mm");

        jLabel6.setText("Nº DNI Empleado:");

        labelDniEmpleado.setText("Numero");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtSPC.setText("SPC");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("REGISTRO DE VENTA");

        jLabel15.setText("IGV: S/.");

        jLabel16.setText("OP Gravada: S/.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAgregar)
                                                .addGap(26, 26, 26)
                                                .addComponent(btnEliminar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(LabelMarca))))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(LabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnLimpiar)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(103, 103, 103))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelDniEmpleado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(7, 7, 7)
                                        .addComponent(labelIdVenta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel13))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelHora)
                                            .addComponent(labelFecha))))
                                .addGap(114, 114, 114)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(53, 53, 53)
                .addComponent(btnRegistar)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIGV)
                            .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelDniEmpleado)
                    .addComponent(jLabel5)
                    .addComponent(labelIdVenta))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(LabelCantidad)
                                    .addComponent(LabelMarca))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(txtProdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProdPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar)
                            .addComponent(txtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelFecha))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(labelHora))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnRegistar)
                    .addComponent(btnSalir))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      
        if(Integer.parseInt(txtcantidad.getText()) <= Integer.parseInt(LabelCantidad.getText())){
            double m;
            int a;
            double igv=0;
            double total_venta=0;
            m = Double.parseDouble(txtcantidad.getText())* Double.parseDouble(txtProdPrecio.getText());
            a = Integer.parseInt(LabelCantidad.getText())- Integer.parseInt(txtcantidad.getText());
            double suma = 0;
            String[]info = new String[6];
            info[0] = txtcantidad.getText();
            info[1] = txtProdCodigo.getText();
            info[2] = txtProdNombre.getText();
            info[3] = txtMarca.getText();
            info[4] = String.valueOf(m);
            info[5] = String.valueOf(a);
            modelo.addRow(info);
            for(int i=0;i<modelo.getRowCount();i++){
                suma = suma + Double.parseDouble(TablaProductos.getValueAt(i, 4).toString());
                
                txtTotal.setText(String.valueOf(Math.round(suma*100.0)/100.0));
                txtIGV.setText(String.valueOf(Math.round((suma*0.18)*100.0)/100.0 ));
                txtTotalVenta.setText(String.valueOf(Math.round((suma*1.18)*100.0)/100.0 ));
            }      
        }
        else{
            JOptionPane.showMessageDialog(null, "esta excediendo del stock disponible");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        txtTotal.setText("0");
        txtIGV.setText("0");
        txtTotalVenta.setText("0");
        
        int fila = TablaProductos.getSelectedRow();
        if(fila>=0){
            modelo.removeRow(fila);
            //JOptionPane.showMessageDialog(null,TablaProductos.getSelectedRow());
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        }
        
        double suma = 0;
        for(int i=0;i<modelo.getRowCount();i++){
            
            
            suma = suma + Double.parseDouble(TablaProductos.getValueAt(i, 4).toString());
            txtTotal.setText(String.valueOf(Math.round(suma*100.0)/100.0));
            txtIGV.setText(String.valueOf(Math.round((suma*0.18)*100.0)/100.0 ));
            txtTotalVenta.setText(String.valueOf(Math.round((suma*1.18)*100.0)/100.0 ));
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxCategoriaItemStateChanged
        
        if(cmbxCategoria.getSelectedIndex()==0){
            CNProd.Mtd_Sin_Categoria(cmbxProducto);
            LabelMarca.setText("");
            LabelCantidad.setText("");
            btnAgregar.setEnabled(false);
        }else{
           ClsECategoria cate = (ClsECategoria)this.cmbxCategoria.getSelectedItem();
           int id_cate = cate.getId_cate();
           //CNProd.Mtd_listar_producto(cmbxProducto, id_cate);
           btnAgregar.setEnabled(true);
        }
    }//GEN-LAST:event_cmbxCategoriaItemStateChanged

    private void cmbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxCategoriaActionPerformed

    }//GEN-LAST:event_cmbxCategoriaActionPerformed

    private void cmbxProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxProductoItemStateChanged

        ClsEProducto prod = (ClsEProducto)this.cmbxProducto.getSelectedItem();
        String nom = prod.getNombre();
        int id_prod = prod.getId();
       // String mar = prod.getMarca();
        int s = prod.getStock();
        double precio = prod.getPrecio_venta();
        //LabelMarca.setText(mar);
        LabelCantidad.setText(String.valueOf(s));
        txtProdNombre.setText(nom);
        //txtMarca.setText(mar);
        txtProdCodigo.setText(String.valueOf(id_prod));
        txtProdPrecio.setText(String.valueOf(precio));
        txtcantidad.setText("1");

    }//GEN-LAST:event_cmbxProductoItemStateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ResultSet rs;
        ClsECliente objEc=new ClsECliente();
        ClsNCliente objNc=new ClsNCliente();

            int flag = 0;
        
            try {
                objEc.setDni(Integer.parseInt(txtDniCliente.getText()));
                flag = 1;
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Ingrese el Nro de DNI correctamente");
            }

            if (flag==1){
                if (objNc.MtdValidarCliente(objEc)==true)
                {
                    txtDniCliente.setEditable(false);
                    btnNuevoCliente.setEnabled(false);
                    txtNombreCliente.setEnabled(true);
                    txtApellidosCliente.setEnabled(true);
                    rs=objNc.MtdBucarCliente(objEc);

                    try {
                        while (rs.next())
                        {
                            txtNombreCliente.setText(rs.getString("nombre"));
                            txtApellidosCliente.setText(rs.getString("apellidos"));
                        }
                    } catch (SQLException ex) {
                        System.out.println(ex);
                    }
                } 
                else
                {
                     JOptionPane.showMessageDialog(null,"No hay registro del cliente");
                }  
            }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        txtNombreCliente.setEditable(true);
        txtApellidosCliente.setEditable(true);
        txtNombreCliente.setEnabled(true);
        txtApellidosCliente.setEnabled(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnClienteCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteCancelarActionPerformed
        txtDniCliente.setText("");
        txtNombreCliente.setText("");
        txtApellidosCliente.setText("");
        txtDniCliente.setEditable(true);
        txtNombreCliente.setEditable(false);
        txtApellidosCliente.setEditable(false);
        txtNombreCliente.setEnabled(false);
        txtApellidosCliente.setEnabled(false);
        btnNuevoCliente.setEnabled(true);
    }//GEN-LAST:event_btnClienteCancelarActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        
        if(modelo.getRowCount()>0){
            MtdImprimir();
        
            String fecha="";
            objECliente.setDni(Integer.parseInt(txtDniCliente.getText().toUpperCase()));        
            objECliente.setNombres(txtNombreCliente.getText().toUpperCase());
            objECliente.setApellidos(txtApellidosCliente.getText().toUpperCase());

            objEStock.setMarca(LabelMarca.getText().toUpperCase());
            JOptionPane.showMessageDialog(null,"dato de cliente guardado");
            objEStock.setStock(Integer.parseInt(LabelCantidad.getText().toUpperCase()));
            fecha=labelFecha.getText().toUpperCase()+" "+ labelHora.getText().toUpperCase();


            objEVenta.setTotal(Double.parseDouble(txtTotalVenta.getText().toUpperCase()));
            objEVenta.setFecha(fecha);
            objEVenta.setCliente_dni(Integer.parseInt(txtDniCliente.getText().toUpperCase()));
            objEVenta.setEmpleado_dni(Integer.parseInt(labelDniEmpleado.getText().toUpperCase()));

            if (objNventa.MtdRegistrarCliente(objECliente)==true)
            {
                //JOptionPane.showMessageDialog(null,"dato de cliente guardado");
            }
            else{
                JOptionPane.showMessageDialog(null,"ocurrio un error en guardar cliente");
            }

            if (objNventa.MtdRegistrarVenta(objEVenta)==true)
            {
                //JOptionPane.showMessageDialog(null,"dato de venta guardado");
            }
            else{
                JOptionPane.showMessageDialog(null,"ocurrio un error en guardar venta");
            }

            for(int i=0;i<modelo.getRowCount();i++){
                objEDVenta.setCantidad(Integer.parseInt(TablaProductos.getValueAt(i, 0).toString()));
                objEDVenta.setTotal_prod(Double.parseDouble(TablaProductos.getValueAt(i, 4).toString()));
                objEDVenta.setVenta_id(Integer.parseInt(labelIdVenta.getText().toUpperCase()));
                objEDVenta.setProducto_id(Integer.parseInt(TablaProductos.getValueAt(i, 1).toString()));
                objNventa.MtdRegistrarDetalleVenta(objEDVenta);   
            }

            for(int i=0;i<modelo.getRowCount();i++){

                objEProducto.setStock(Integer.parseInt(TablaProductos.getValueAt(i, 5).toString()));
                objEProducto.setId(Integer.parseInt(TablaProductos.getValueAt(i, 1).toString()));
                objNventa.MtdActualizarStock(objEProducto);          
            } 

            MtdReset();
        }else{
            JOptionPane.showMessageDialog(null,"no agrego ningun producto para la venta");
        }
        
        
        
    }//GEN-LAST:event_btnRegistarActionPerformed

    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        MtdReset();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        MtdlimpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmLogin log = new FrmLogin();
        log.show();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void MtdImprimir(){
        Boleta bolet = new Boleta();
        impresion imp = new impresion();
        imp.show();

        Boleta.labelDni.setText(txtDniCliente.getText());
        Boleta.labelNro.setText(labelIdVenta.getText());
        Boleta.labelFecha.setText(labelFecha.getText());
        Boleta.txtTotal.setText(txtTotal.getText());
        Boleta.Nombre.setText(txtNombreCliente.getText()+" "+txtApellidosCliente.getText());
        Boleta.txtTotalVenta.setText(txtTotalVenta.getText());
        Boleta.txtIGV.setText(txtIGV.getText());
        
        
        for(int i=0;i<modelo.getRowCount();i++){
            
            String Datos[] = new String[3];
            Datos[0]=TablaProductos.getValueAt(i, 0).toString();
            Datos[1]=TablaProductos.getValueAt(i, 2).toString();
            Datos[2]=TablaProductos.getValueAt(i, 4).toString();            
            bolet.modelo1.addRow(Datos); 
   
        }
    }
        
    private void MtdlimpiarTabla(){
        modelo.getDataVector().removeAllElements();
        TablaProductos.updateUI();
    }
    
    private void MtdId_venta() {
        labelIdVenta.setText("1");
        ResultSet rs;
        ClsNVenta objId=new ClsNVenta();
        rs=objId.MtdIdVenta();
        int incremento;
        try {
            while (rs.next())
            {
                incremento = rs.getInt("id")+1;
                labelIdVenta.setText(String.valueOf(incremento));               
            }
        } catch (SQLException ex) {
                System.out.println(ex);
        }
    }
    
    private void MtdReset(){
        LabelMarca.getText();
        txtProdNombre.setVisible(false);
        txtMarca.setVisible(false);
        txtProdCodigo.setVisible(false);
        txtProdPrecio.setVisible(false);
        cmbxCategoria.setSelectedIndex(0);
        txtcantidad.setText("1"); 
        txtTotal.setText("0");
        txtTotal.setEditable(false);
        txtDniCliente.setEditable(true);
        btnNuevoCliente.setEnabled(true);
        txtDniCliente.setText("");
        txtNombreCliente.setText("");
        txtNombreCliente.setEnabled(false);
        txtApellidosCliente.setEnabled(false);
        txtApellidosCliente.setText("");
        txtNombreCliente.setEditable(false);
        txtApellidosCliente.setEditable(false);
        btnAgregar.setEnabled(false);
        txtIGV.setText("0");
        txtIGV.setEditable(false);
        txtTotalVenta.setText("0");
        txtTotalVenta.setEditable(false);
        
        MtdId_venta();
        MtdlimpiarTabla();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCantidad;
    private javax.swing.JLabel LabelMarca;
    public static javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClienteCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbxCategoria;
    private javax.swing.JComboBox<String> cmbxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelDniEmpleado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelIdVenta;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtProdCodigo;
    private javax.swing.JTextField txtProdNombre;
    private javax.swing.JTextField txtProdPrecio;
    private javax.swing.JTextField txtSPC;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalVenta;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
